.ace: &ace
  tags: ['ace-x86_64']

stages:
  - test

image: d2s://external/docker/debian:bookworm

test:
  <<: *ace
  stage: test
  variables:
    SCALENODE_CPU: 1
    SCALENODE_RAM: 1024
    SCALENODE_DISK: 1
  before_script:
    - apt-get update
    - apt-get install -y lua-check tshark python3-pip git
  script:
    - pip install --break-system-packages git+https://github.com/antmicro/tuttest
    - tuttest README.md install | sh
    - luacheck *.lua
    - tuttest README.md test | sh | diff --color -uw - <(tuttest README.md gold)
